### PR TITLE
Allow for reading from bytestrings with fix for parsing

### PR DESCRIPTION
**Pull request by GregorySchwartz**
Solves #6 and also a bug where if the file has no end of line at the end of input the last line is not parsed.

### CODE REVIEW

**Comment by GregorySchwartz** [comment]
Is it possible for this pull request to get accepted and pushed to Hackage soon? I want to use a non-local version before release of some code.

**Review by ocramz — APPROVED** [review]
Thanks!

**Comment by ocramz** [comment]
@GregorySchwartz new version on Hackage !

**Comment by GregorySchwartz** [comment]
I forgot to export the functions in the non-internal file!

**Pull request merged**
